name: Test workflow_run second
on:
  workflow_run:
    workflows:
      - Test workflow_run first
    types:
      - completed

jobs:
  world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test second xxx"