name: Test workflow_run second
on:
  workflow_run:
    workflows:
      - workflow-run-first
    types:
      - completed

jobs:
  world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test second"